### ISSUE TITLE
Tax Account Issue [BUG]

### ISSUE THREAD

**Issue by Crumpeh** [KaiKikuchi/QuickShop#105]
I'm using the latest version (0.9.29) as well as Minecraft 1.11.2 with Iconomy 7.

I set up everything perfectly and it was working fine, the taxrate was at 20% and the tax account was working fine, if a player sold something they would pay taxes and the tax account would recieve the money. After closing the server and reopening the next day (no changes to any files or any settings) upon going to my shop area I noticed that the tax account was no longer receiving money when people were selling things to the shop.

Things I have tried:
- Double checked both tax account is under the same name
- Checked the tax feature is enabled.
- Checked the database to make sure there are no corruptions.
- Downloading clean version and default config.

If anyone has had a similar issue and knows how to fix please let me know!

**Comment by KaiKikuchi** [comment]
Have you checked the server logs for exceptions related to your issue with QuickShop?

**Comment by Crumpeh** [comment]
The only issue being logged to the console was this:
```
[22:48:39] [Server thread/WARN]: [QuickShop] Task #357 for QuickShop v0.9.29 generated an exception
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.valueOf(Unknown Source) ~[?:1.8.0_121]
	at com.iCo6.IO.mini.Arguments.getDouble(Arguments.java:58) ~[?:?]
	at com.iCo6.system.Queried.getBalance(Queried.java:340) ~[?:?]
	at com.iCo6.system.Holdings.getBalance(Holdings.java:22) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_iConomy6.getBalance(Economy_iConomy6.java:129) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy_Vault.getBalance(Economy_Vault.java:106) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy.getBalance(Economy.java:117) ~[?:?]
	at org.maxgamer.quickshop.Shop.ShopManager$1.run(ShopManager.java:526) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[22:48:45] [Server thread/WARN]: [QuickShop] Task #358 for QuickShop v0.9.29 generated an exception
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.valueOf(Unknown Source) ~[?:1.8.0_121]
	at com.iCo6.IO.mini.Arguments.getDouble(Arguments.java:58) ~[?:?]
	at com.iCo6.system.Queried.getBalance(Queried.java:340) ~[?:?]
	at com.iCo6.system.Holdings.getBalance(Holdings.java:22) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_iConomy6.getBalance(Economy_iConomy6.java:129) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy_Vault.getBalance(Economy_Vault.java:106) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy.getBalance(Economy.java:117) ~[?:?]
	at org.maxgamer.quickshop.Shop.ShopManager$1.run(ShopManager.java:526) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[22:48:51] [Server thread/WARN]: [QuickShop] Task #359 for QuickShop v0.9.29 generated an exception
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.valueOf(Unknown Source) ~[?:1.8.0_121]
	at com.iCo6.IO.mini.Arguments.getDouble(Arguments.java:58) ~[?:?]
	at com.iCo6.system.Queried.getBalance(Queried.java:340) ~[?:?]
	at com.iCo6.system.Holdings.getBalance(Holdings.java:22) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_iConomy6.getBalance(Economy_iConomy6.java:129) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy_Vault.getBalance(Economy_Vault.java:106) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy.getBalance(Economy.java:117) ~[?:?]
	at org.maxgamer.quickshop.Shop.ShopManager$1.run(ShopManager.java:526) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[22:48:52] [Netty Server IO #4/INFO]:  [0;30;22m([0;31;22mAdmin[0;30;22m)[0;37;22m [0;35;22mCrumpeeeh: [0;30;1m64[m
[22:48:57] [Server thread/WARN]: [QuickShop] Task #360 for QuickShop v0.9.29 generated an exception
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Double.valueOf(Unknown Source) ~[?:1.8.0_121]
	at com.iCo6.IO.mini.Arguments.getDouble(Arguments.java:58) ~[?:?]
	at com.iCo6.system.Queried.getBalance(Queried.java:340) ~[?:?]
	at com.iCo6.system.Holdings.getBalance(Holdings.java:22) ~[?:?]
	at com.iCo6.system.Holdings.add(Holdings.java:55) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_iConomy6.depositPlayer(Economy_iConomy6.java:157) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy_Vault.deposit(Economy_Vault.java:77) ~[?:?]
	at org.maxgamer.quickshop.Economy.Economy.deposit(Economy.java:102) ~[?:?]
	at org.maxgamer.quickshop.Shop.ShopManager$1.run(ShopManager.java:473) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Bukkit-4d3bf20]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[22:49:07] [Server thread/INFO]: [0;32;1mReloading...[m
[22:49:07] [Server thread/INFO]: [QuickShop] Disabling QuickShop v0.9.29
```

**Comment by KaiKikuchi** [comment]
Please can you post your Vault and iConomy versions? It's probably a bug related to that, as QuickShop is just passing the player and a double value to Vault. And Vault is passing that to iConomy. And iConomy is failing to parse a String to double. Why would it do such thing? Anyway, 99% it's a bug related to iConomy. Try with [SaneEconomy](https://www.spigotmc.org/resources/saneeconomy-simple-but-featureful-economy.26223/) instead. I use it and works very well.

**Comment by KaiKikuchi** [comment]
I'm closing this because it seems a server configuration issue or a bad economy plugin more than anything else.
