### ISSUE TITLE
Version Error with Spigot 1.12 preRelease Build

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#123]
[08:56:31] [Server thread/INFO]: [QuickShop] Enabling QuickShop v0.9.29
[08:56:31] [Server thread/ERROR]: Error occurred while enabling QuickShop v0.9.29 (Is it up to date?)
java.lang.UnsupportedClassVersionError: This version of QuickShop is incompatible. Internal version: v1_12_R1
	at org.maxgamer.quickshop.Util.NMS.init(NMS.java:462) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:131) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-451

**Comment by KaiKikuchi** [comment]
Done in v.0.9.30
