### ISSUE TITLE
old SQL from old quickshop 4.4 not work (string username not uuid)

### ISSUE THREAD

**Issue by FlashLight34** [KaiKikuchi/QuickShop#13]
[02:25:35] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid UUID string: Darkgrill
[02:25:35] [Server thread/WARN]:    at java.util.UUID.fromString(UUID.java:194)
[02:25:35] [Server thread/WARN]:    at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:227)
[02:25:35] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[02:25:35] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[02:25:35] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[02:25:35] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[02:25:35] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins

with quickshop 4.4 : [02:32:46] [Server thread/INFO]: [QuickShop] Loaded 4012 shops.

with quickshop notlikeme 9.8 [02:32:46] [Server thread/INFO]: [QuickShop] Loaded 0 shops. and many errors so maybe we need to detect this with a try catch and convert name of player with getplayeroffline(string) and set this to UUID.tostring() :)

**Comment by FlashLight34** [comment]
example of the old format of the sql from quickshop 4.4
INSERT INTO `shops` (`owner`, `price`, `itemConfig`, `x`, `y`, `z`, `world`, `unlimited`, `type`) VALUES
('GrixleFourbe', 1.00, 0x6974656d3a0a20203d3d3a206f72672e62756b6b69742e696e76656e746f72792e4974656d537461636b0a2020747970653a204d454c4f4e0a, -1640, 64, 668, 'worldust2', 0, 0),
('Roubix', 2.00, 0x6974656d3a0a20203d3d3a206f72672e62756b6b69742e696e76656e746f72792e4974656d537461636b0a2020747970653a2042414b45445f504f5441544f0a, -1640, 64, 670, 'worldust2', 0, 0),

**Comment by FlashLight34** [comment]
in your 227 line from quickshop.java  
Shop shop = new ContainerShop(loc, price, item, UUID.fromString(owner));
UUID uuidowner = null;
try {
uuidowner = UUID.fromString(owner)
}catch(Exception e){
//Convert owner
getLogger().info("Converting old Owner shop...");
Player plon = getServer().getplayer(owner)
if (plon != null) uuidowner = plon.getUniqueId();
else uuidowner = getServer().GetOffPlayer(owner).getUniqueId();
}
    public OfflinePlayer GetOffPlayer(String name){
        for (OfflinePlayer pl:getServer().getOfflinePlayers()) {
            if (pl.getName().equalsIgnoreCase(name)) {
                return pl;
            }
        }
        return null;
    }

before that line

and replace your 227 line 
if (uuidowner == null) {
//delete de shop
getLogger().warning("Owner of this shop not found deleted him... "+owner);
//code for delete the shop
continue;
}
Shop shop = new ContainerShop(loc, price, item, uuidowner);

**Comment by KaiKikuchi** [comment]
QuickShop 9.8 doesn't support old QuickShop 4 data.

The old QuickShop is not using UUIDs, that's why you get that error.

**Comment by FlashLight34** [comment]
ok man i add this my self thx for your help

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/QuickShop/issues/17
