### ISSUE TITLE
Essentials Enderchest Error

### ISSUE THREAD

**Issue by xXSchrandXx** [KaiKikuchi/QuickShop#142]
Hi, 
everytime a Player performes the /enderchest kommand on my Server, your plugin Displays this error: `
[22:02:35] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to QuickShop v0.9.33
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:886) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1657) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_12_R1.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.getLocation(CraftInventory.java:504) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.maxgamer.quickshop.Listeners.PlayerListener.onInventoryClose(PlayerListener.java:212) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor463.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
	... 16 more`

**Comment by KaiKikuchi** [comment]
You are not using the latest version: https://github.com/KaiKikuchi/QuickShop/releases
