### ISSUE TITLE
Spigot 1.13 with QS 0.9.35 incompatible error

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#178]
[07:39:08 INFO]: [QuickShop] Enabling QuickShop v0.9.35
[07:39:08 ERROR]: Error occurred while enabling QuickShop v0.9.35 (Is it up to date?)
java.lang.UnsupportedClassVersionError: This version of QuickShop is incompatible. Internal version: v1_13_R1
        at org.maxgamer.quickshop.Util.NMS.init(NMS.java:553) ~[?:?]
        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:136) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13-22-July-2018_2.jar:git-Spigot-5eb3921-b50bb15]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by kaiarne** [comment]
same thing happens on our testserver; we don't plan to update until spigot wave 2, a fix within time would be very nice

**Comment by KaiKikuchi** [comment]
Unfortunately, the new Bukkit API 1.13 got few changes that broke the possibility of having a backward compatible plugin... this means that newer versions of QuickShop will probably be only 1.13 compatible.

Also, the config will need few changes too... especially regarding the items blacklist (cannot be numeric IDs anymore).

I can't give any ETA, but I'll try to make a 1.13 only version.

More info: https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-development-builds.328883/

**Comment by smmmadden** [comment]
That's what most others are doing @KaiKikuchi - stopping on 1.12 for the last version and then creating a new version for 1.13+ as well as not bug fixing the older after 1.13 is done.

**Comment by smmmadden** [comment]
latest build is working, but there are two changes to make in the config.yml file these lines:
[92] - 7 #Bedrock
should now be: - Bedrock

[102] NETHER_STALK;Nether Wart;Nether Wart
should now be: NETHER_WART_BLOCK

These changes will fix the follow errors at startup.
[22:05:32 INFO]: [QuickShop] Found permission provider.
[22:05:32 INFO]: [QuickShop] 7 is not a valid material.  Check your spelling or ID
[22:05:32 WARN]: Invalid custom item name definition {NETHER_STALK;Nether Wart;Nether Wart} Error: Invalid material: NETHER_STALK

**Comment by KaiKikuchi** [comment]
Hey. Sorry I forgot to mention that on the update notes. You cannot use numeric IDs anymore.

**Comment by smmmadden** [comment]
yeah, I knew that which is how I found it.  This is default file that is in the jar.  I didn't have it installed until I saw you updated it, so the errors are from first use install. :-)
