### ISSUE TITLE
Could not pass event InventoryCloseEvent to QuickShop

### ISSUE THREAD

**Issue by Gerlif** [KaiKikuchi/QuickShop#184]
Previously reported in #132. Seems to be back?

```
10.11 01:50:44 [Server] ERROR Could not pass event InventoryCloseEvent to QuickShop vReremake 1.3.0
10.11 01:50:44 [Server] INFO org.bukkit.event.EventException: null
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:963) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1924) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
10.11 01:50:44 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
10.11 01:50:44 [Server] INFO Caused by: java.lang.NullPointerException
10.11 01:50:44 [Server] INFO at org.maxgamer.quickshop.Shop.ShopManager.getShop(ShopManager.java:143) ~[?:?]
10.11 01:50:44 [Server] INFO at org.maxgamer.quickshop.Listeners.PlayerListener.invCloseEvent(PlayerListener.java:377) ~[?:?]
10.11 01:50:44 [Server] INFO at sun.reflect.GeneratedMethodAccessor283.invoke(Unknown Source) ~[?:?]
10.11 01:50:44 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
10.11 01:50:44 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
10.11 01:50:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
10.11 01:50:44 [Server] INFO ... 16 more
```

**Comment by KaiKikuchi** [comment]
This is not related to this version of QuickShop.
