### ISSUE TITLE
Brush of a suspended object BUG

### ISSUE THREAD

**Issue by edcsg** [KaiKikuchi/QuickShop#21]
Thank you very much for your attention, a BUG in the presence of 1.7.X, which may be unable to speak clearly. Let me take the picture below.

Picture link:http://img.gg/9L9UDam

<Also thank you for the 0.9.10 version update, but it looks like a mistake could not be loaded>

[22:21:01] [Server thread/ERROR]: Could not load 'plugins\QuickShop-0.9.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `org.maxgamer.quickshop.QuickShop'
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
    at net.minecraft.world.World.<init>(World.java:349) [ahb.class:?]
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: Failed to remap class org.maxgamer.quickshop.QuickShop
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    ... 12 more
Caused by: java.lang.UnsupportedClassVersionError: org/maxgamer/quickshop/QuickShop : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_79]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_79]
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:476) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:git-Cauldron-Reloaded-1

**Comment by KaiKikuchi** [comment]
Thank you for reporting both bugs.
I suggest you to disable 'display-items' in your config.yml

**Comment by KaiKikuchi** [comment]
Also, are you using Java 1.7? Try updating to 1.8. Also support for version older than MC 1.7.9 was removed in QuickShop v.0.9.10.

**Comment by edcsg** [comment]
Yes, I'll try to update it to 1.8

**Comment by KaiKikuchi** [comment]
This bug got fixed on v 0.9.20
