### ISSUE TITLE
Clearing shops with WE aren't deleted properly

### ISSUE THREAD

**Issue by TNTUP** [KaiKikuchi/QuickShop#46]
Hey, this is an issue I have since 1.8, when I clear expired player shops with worldedit, it removes it but QS still have it in the db so it spam the console on startup or while /qs reload.

When I start the server or doing /qs reload, it gives me alot of invalid chestshops which doesn't exist, it says Deleting. but everytime I restart it comes back.

Here's the stacktrace for you :)

[01:48:43] [Server thread/ERROR]: [QuickShop] Error loading a shop! Coords: world (-161, 66, 764)...
[01:48:43] [Server thread/ERROR]: [QuickShop] Multiple errors in shops - Something seems to be wrong with your shops database! Please check it out immediately!
[01:48:43] [Server thread/WARN]: java.sql.SQLException: near "LIMIT": syntax error
[01:48:43] [Server thread/WARN]:    at org.sqlite.NativeDB.throwex(NativeDB.java:210)
[01:48:43] [Server thread/WARN]:    at org.sqlite.NativeDB._exec(Native Method)
[01:48:43] [Server thread/WARN]:    at org.sqlite.Stmt.executeUpdate(Stmt.java:152)
[01:48:43] [Server thread/WARN]:    at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:235)
[01:48:43] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[01:48:43] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[01:48:43] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:48:43] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[01:48:43] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[01:48:43] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[01:48:43] [Server thread/INFO]: [QuickShop] Shop is not an InventoryHolder in world at: -177, 66, 743.  Deleting.
[01:48:43] [Server thread/WARN]: java.sql.SQLException: near "LIMIT": syntax error
[01:48:43] [Server thread/WARN]:    at org.sqlite.NativeDB.throwex(NativeDB.java:210)
[01:48:43] [Server thread/WARN]:    at org.sqlite.NativeDB._exec(Native Method)
[01:48:43] [Server thread/WARN]:    at org.sqlite.Stmt.executeUpdate(Stmt.java:152)
[01:48:43] [Server thread/WARN]:    at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:235)
[01:48:43] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[01:48:43] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[01:48:43] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:48:43] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[01:48:43] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[01:48:43] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[01:48:43] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)

I understand at those coords is invalid, that shop was deleted using WE so can QS detect if those inexistant shops gets removed from the db on startup? It should say "Invalid XXXX at coords, deleting" rather than printing the entire stacktrace and seeing it once. Instead, I see it on every server restarts

PS: sorry for my poor english :x

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your report!

**Comment by TNTUP** [comment]
Woah! Didn't expected a quick fix! I'll keep an eye on BukkitDev to download it^^

**Comment by KaiKikuchi** [comment]
It'll take a lot of time there. You can download it from here: https://github.com/KaiKikuchi/QuickShop/releases/tag/v.0.9.15

**Comment by TNTUP** [comment]
Haha okay! Thanks for this quick fix :)
