### ISSUE TITLE
It's not loading with 1.9 for me?

### ISSUE THREAD

**Issue by cowsook** [KaiKikuchi/QuickShop#48]
With 1.9-R0.1-SNAPSHOT

On server startup:

[00:02:29] [Server thread/ERROR]: Could not load 'plugins/QuickShop-0.9.14.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/maxgamer/quickshop/QuickShop : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-5d4e372-9554894]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-5d4e372-9554894]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-5d4e372-9554894]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-5d4e372-9554894]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-5d4e372-9554894]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-5d4e372-9554894]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
Caused by: java.lang.UnsupportedClassVersionError: org/maxgamer/quickshop/QuickShop : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_85]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_85]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_85]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_85]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_85]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_85]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_85]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_85]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_85]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-5d4e372-9554894]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-5d4e372-9554894]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_85]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_85]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_85]
    at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_85]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-5d4e372-9554894]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-5d4e372-9554894]
    ... 6 more

**Comment by KaiKikuchi** [comment]
You should read closed tickets before opening a new one.

Any proper administrator would make sure to have important stuff like Java updated to the latest stable version.

https://github.com/KaiKikuchi/QuickShop/issues/45

Also you're not running the latest version of this plugin.
