### ISSUE TITLE
NullPointerException when using shop with non-standard name

### ISSUE THREAD

**Issue by john01dav** [KaiKikuchi/QuickShop#6]
When a shop is given a name that doesn't actually exist (ie. adminshop) so that the money from the shop doesn't go to any player, the plugin throws a NullPointerException. 

It is an easy fix, simply change line 146 in MsgUtil from:

```
p.sendMessage(ChatColor.DARK_PURPLE + "| " + MsgUtil.getMessage("menu.owner", Bukkit.getOfflinePlayer(shop.getOwner()).getName()));
```

to

```
try{
    p.sendMessage(ChatColor.DARK_PURPLE + "| " + MsgUtil.getMessage("menu.owner",     Bukkit.getOfflinePlayer(shop.getOwner()).getName()));
}catch(NullPointerException e){
    p.sendMessage(ChatColor.DARK_PURPLE + "| " + MsgUtil.getMessage("menu.owner", shop.getOwner());
}
```

I tried to fork the repository to implement this change myself as a pull request, but the files in the repository are out of sync (specifically MsgUtil refers to a class called Shop that doesn't exist).

**Comment by KaiKikuchi** [comment]
Bukkit.getOfflinePlayer(UUID) will always return an OfflinePlayer object, and getName() may return null, but it won't throw a NullPointerException.
getMessage() accepts "null" on the second parameter so it won't throw an Exception so... I need the exception that you get on your server log.

PS: your solution works but it's not the best way.

**Comment by john01dav** [comment]
Here's the error log:

```
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1420.99]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1420.99]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1420.99]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1420.99]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1420.99]
    at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:159) [mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:732) [nh.class:?]
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) [ji.class:?]
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) [ji.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
    at java.lang.String.replace(String.java:2240) ~[?:1.8.0_60]
    at org.maxgamer.quickshop.Util.MsgUtil.getMessage(MsgUtil.java:279) ~[?:?]
    at org.maxgamer.quickshop.Util.MsgUtil.sendShopInfo(MsgUtil.java:146) ~[?:?]
    at org.maxgamer.quickshop.Util.MsgUtil.sendShopInfo(MsgUtil.java:136) ~[?:?]
    at org.maxgamer.quickshop.Listeners.PlayerListener.onClick(PlayerListener.java:82) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1420.99]
    ... 15 more
```

Also, getMessage() doesn't accept null on the second parameter as it then feeds that null into String#replace() as it's second parameter which is what throws the NullPointerException. 

I know that my solution isn't the best, but much if this codebase is that way (ie. uppercase package names) and it was the easiest to place in an issue. Taking these two things together, I figured it's best to post it the way I did. If you want to fix it your way, I'm fine with that -- I was simply suggesting one way to fix it.

**Comment by KaiKikuchi** [comment]
... what version are you using?
There's a null check:
https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/java/org/maxgamer/quickshop/Util/MsgUtil.java#L275

**Comment by KaiKikuchi** [comment]
Anyway, I'm gonna fix it.

**Comment by john01dav** [comment]
That null check only checks if the entire array is null -- not each element in the array.

Here would be the correct way to do it:

```
public static String getMessage(String loc, String... args){
    String raw = messages.getString(loc);
    if(raw == null || raw.isEmpty()){
        return "Invalid message: " + loc;
    }

    if(args == null){
        return raw;
    }

    for(int i = 0; i < args.length; i++){
        if(args[i] != null){
            raw = raw.replace("{" + i + "}", args[i]);
        }
    }

    return raw;
}
```

Also, if you do that it will fix the NPE but another bug will appear; the tag in the message format for the name of the offline player won't be replaced at all (I can change the above method to replace it with "null" if you want, but that's not much better). You will need to do another if statement to check if the OfflinePlayer's getName() method returns null, and if so to use the string that would normally be a UUID in the message instead.

**Comment by john01dav** [comment]
Do you have a new build available for this? BukkitDev hasen't approved it if you uploaded it there. I can't build it myself due to a maven misconfiguration (http://pastebin.com/jQ5SkBf8) regarding your dependencies. I can't even add them myself since you have no dependency list.

**Comment by KaiKikuchi** [comment]
http://kaikk.net/mc/
