### ISSUE TITLE
can't use at spigot-1.10.Hope you can fix it.Thanks

### ISSUE THREAD

**Issue by assidence** [KaiKikuchi/QuickShop#67]
[17:58:52 ERROR]: Error occurred while enabling QuickShop v0.9.18 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
    at org.maxgamer.quickshop.Economy.Economy_Vault.setupEconomy(Economy_Vault.java:19) ~[?:?]
    at org.maxgamer.quickshop.Economy.Economy_Vault.<init>(Economy_Vault.java:15) ~[?:?]
    at org.maxgamer.quickshop.QuickShop.loadEcon(QuickShop.java:437) ~[?:?]
    at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:132) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10.jar:git-Spigot-e50d38c-fb568fd]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
    ... 15 more
[17:58:52 INFO]: [Essentials] Enabling Essentials v2.0.1-b357

**Comment by KaiKikuchi** [comment]
You are not using Vault and an Economy plugin that supports Vault.

Also you are not using the latest version of QuickShop.
