### ISSUE TITLE
Error with 1.10

### ISSUE THREAD

**Issue by Beaupedia** [KaiKikuchi/QuickShop#69]
Based on a previous reply I saw here in the tickets, I thought the plugin was compatible with 1.10. We've updated and now receive the following error:

`[16:37:08] [Server thread/ERROR]: Error occurred while enabling QuickShop v0.9.21 (Is it up to date?)
java.lang.UnsupportedClassVersionError: This version of QuickShop is incompatible. Internal version: v1_10_R1
    at org.maxgamer.quickshop.Util.NMS.init(NMS.java:282) ~[?:?]
    at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:127) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-c55900f-9af379f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]`

We're using the latest available Vault that I can see and we're using the latest version of QuickShop.

We're huge fans of QuickShop and really want to use it for a special event we have on Saturday, any suggestions?

**Comment by KaiKikuchi** [comment]
Hello! Thank you for your report.

Please try this: https://github.com/KaiKikuchi/QuickShop/releases/tag/v.0.9.22-DEV-1

Let me know if this build fixes the issue with Bukkit 1.10

**Comment by Beaupedia** [comment]
That seems to have done the trick! Thank you!!!
