### ISSUE TITLE
1.10.2 cannot buy anything from shop.

### ISSUE THREAD

**Issue by mattigins** [KaiKikuchi/QuickShop#77]
The plugin runs fine but when i try to purchase from a shop i get this in the console. (Tried other versions too, same problem)

`[Server thread/WARN]: [QuickShop] Task #1165026 for QuickShop v0.9.22-DEV-1 generated an exception
java.lang.LinkageError: loader constraint violation: when resolving method "org.maxgamer.quickshop.Shop.ShopPurchaseEvent.<init>(Lorg/maxgamer/quickshop/Shop/Shop;Lorg/bukkit/entity/Player;I)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, org/maxgamer/quickshop/Shop/ShopManager$1, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, org/maxgamer/quickshop/Shop/ShopPurchaseEvent, have different Class objects for the type org/maxgamer/quickshop/Shop/Shop used in the signature
    at org.maxgamer.quickshop.Shop.ShopManager$1.run(ShopManager.java:447) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]`

**Comment by KaiKikuchi** [comment]
You haven't specified what is your server version. Also your java version is old.

I've just tried the latest version of QuickShop with the latest version of spigot for MC 1.10.2, Vault 1.5.6 and SaneEconomy 0.6.5. It works fine.

**Comment by mattigins** [comment]
It says 1.10.2 in the title.  I'll update Java and see what happens

**Comment by KaiKikuchi** [comment]
Use the /version command and copy-paste your server version. Also specify if you are using Spigot, CraftBukkit, or another server version.
