### ISSUE TITLE
Plugin loads but not working

### ISSUE THREAD

**Issue by Devilsphere007** [KaiKikuchi/QuickShop#93]
Plugin loads in but no commands or shops working in game?

[00:05:37] [Server thread/INFO]: [QuickShop] Enabling QuickShop v0.9.27
[00:05:37] [Server thread/INFO]: [QuickShop] Creating messages.yml
[00:05:37] [Server thread/INFO]: [QuickShop] Found permission provider.
[00:05:37] [Server thread/INFO]: [QuickShop] Limit cfg found...
[00:05:37] [Server thread/INFO]: [QuickShop] Limits.use: false
[00:05:37] [Server thread/INFO]: [QuickShop] {quickshop=0, quickshop.vip=20}
[00:05:37] [Server thread/ERROR]: Error occurred while enabling QuickShop v0.9.27 (Is it up to date?)
java.lang.NoClassDefFoundError: org/sqlite/NativeDB
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_102]
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_102]
	at java.lang.System.load(Unknown Source) ~[?:1.8.0_102]
	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:268) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:304) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_102]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_102]
	at org.maxgamer.quickshop.Database.SQLiteCore.getConnection(SQLiteCore.java:39) ~[?:?]
	at org.maxgamer.quickshop.Database.SQLiteCore.getConnection(SQLiteCore.java:55) ~[?:?]
	at org.maxgamer.quickshop.Database.Database.<init>(Database.java:26) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:281) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-16c940b-eed13ca]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: org.sqlite.NativeDB
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	... 33 more

**Comment by KaiKikuchi** [comment]
Hello. It seems you're missing [SQLite library](https://dev.bukkit.org/bukkit-plugins/sqlibrary/). You can either install a library, or use MySQL instead.

**Comment by Devilsphere007** [comment]
Ok thank you for your quick response ill check it out after work. Keep up
the good work on the plugin. Been using it from the start .  If you have a
donate button ill send you some cash :)

**Comment by KaiKikuchi** [comment]
Hey, thank you for your support! You may want to visit my [personal page](http://mc.kaikk.net).
