### ISSUE TITLE
QS throws up a incompatible error on 1.11

### ISSUE THREAD

**Issue by gerardvanschip** [KaiKikuchi/QuickShop#94]
When I do /plugins it shows as loaded but creating shops does not work, nor does the /qs command.

Running Spigot 1.11 and QuickShop 0.9.27

Included the error from console below.

`[09:41:51] [Server thread/INFO]: [QuickShop] Enabling QuickShop v0.9.26
[09:41:51] [Server thread/ERROR]: Error occurred while enabling QuickShop v0.9.26 (Is it up to date?)
java.lang.UnsupportedClassVersionError: This version of QuickShop is incompatible. Internal version: v1_11_R1
at org.maxgamer.quickshop.Util.NMS.init(NMS.java:373) ~[?:?]
at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:127) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[custom.jar:git-Spigot-16c940b-89e6712]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [custom.jar:git-Spigot-16c940b-89e6712]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [custom.jar:git-Spigot-16c940b-89e6712]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [custom.jar:git-Spigot-16c940b-89e6712]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [custom.jar:git-Spigot-16c940b-89e6712]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [custom.jar:git-Spigot-16c940b-89e6712]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [custom.jar:git-Spigot-16c940b-89e6712]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [custom.jar:git-Spigot-16c940b-89e6712]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [custom.jar:git-Spigot-16c940b-89e6712]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [custom.jar:git-Spigot-16c940b-89e6712]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]`

**Comment by KaiKikuchi** [comment]
Well... you're clearly using v.0.9.26. xD

**Comment by gerardvanschip** [comment]
I know, thats why I closed it. For some weird reason Plugman dump said I was running 0.9.27?
