### ISSUE TITLE
display-items: true not working.

### ISSUE THREAD

**Issue by gerardvanschip** [KaiKikuchi/QuickShop#95]
The floating icon above chests stopped working when using the plugin on a 1.11 server. Everything else seems ok.

**Comment by kaiarne** [comment]
One of our Users reported, that he saw the icons for like 0.1sec after porting into the area. Maybe this helps finding the problem. We would very much like to continue using this plugin.

**Comment by jewome62** [comment]
I have ssame problem, i see item for 0.5seconde after nothing

**Comment by gerardvanschip** [comment]
Dying for an update. Of course its super cool that the plugin still functions but the rotating icons are what makes this plugin so special.

**Comment by gerardvanschip** [comment]
[03:48:53] [Server thread/INFO]: [QuickShop] Enabling QuickShop v0.9.27
[03:48:53] [Thread-23/WARN]: [Fatal Error] :1:1: Premature end of file.

[03:48:53] [Thread-23/WARN]: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[03:48:53] [Thread-23/WARN]: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
[03:48:53] [Thread-23/WARN]: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
[03:48:53] [Thread-23/WARN]: 	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
[03:48:53] [Thread-23/WARN]: 	at net.timroden.signedit.VersionChecker.run(VersionChecker.java:44)
[03:48:53] [Thread-23/WARN]: [SignEdit] ?cError retrieving latest version from BukkitDev.

**Comment by KaiKikuchi** [comment]
Hey thank you for your reports.
I am aware of the issue, but I am extremely busy and fixing this issue is not a priority. Please wait few more days/weeks.

@gerardvanschip that "fatal error" is not related to QuickShop but SignEdit's auto-updater.

**Comment by KaiKikuchi** [comment]
Please try version 0.9.29

**Comment by kaiarne** [comment]
The Icons are back and seem stable, thank you very much for upholding this plugin.
